### ISSUE TITLE
Clipper Modern Style - Manager Layout Issues

### ISSUE THREAD

**Issue by bossloper** [ClipperCMS/ClipperCMS#80] opened 2012-11-22 21:45 UTC
A couple of layout issues with IE10

1) The text area boxes on System Configuration pages are either very near to right edge so scroll bar is only just visible or

**Comment by TimGS** [comment] 2012-12-05 22:07
Closed, as I think it is a duplicate of part of issue 81.

**Closed as completed by TimGS** 2012-12-05 22:07 UTC
