### ISSUE TITLE
System info: Database sizes when using innoDB-engine

### ISSUE THREAD

**Issue by ghost** [ClipperCMS/ClipperCMS#282] opened 2013-05-22 13:49 UTC
In Tab "Reports" -> "System Info": Database tables - The sizes are not displayed correctly when using the InnoDB-engine. (same as issue 254)
![bildschirmfoto 2013-05-22 um 15 36 26](https://f.cloud.github.com/assets/2494136/548521/e6f85200-c2e5-11e2-9120-2e813085e61c.png)

**Comment by TimGS** [comment] 2013-05-29 22:46
Can you double check this is with an up to date copy of the develop branch?

Between 'Records' and 'Data Size' should be a new column 'Engine'. As this is missing I think this is just a duplicate of the previous similar issue, seen on an old version of the code.

I have checked with a fresh default install and this works OK.

thanks,
Tim.

**Comment by ghost** [comment] 2013-05-30 14:10
Hi Tim

I have just downloaded the current development version and made a fresh default install.
Sorry, but the Display of database tables in Backup-Section is OK, but in System-Info-Section still the "wrong" table ist displayed. Tested it on 2 different servers.

**Comment by TimGS** [comment] 2013-05-30 18:09
Sorry, my misunderstanding.

**Closed as completed** 2013-06-02 20:55 UTC
Labels: duplicate

**Comment by TimGS** [comment] 2013-06-02 21:11
Fixed. I have also made the two relevant manager actions (system info and backup) use the same database info code to avoid similar situations in future when one gets fixed but the other is forgotten.
