### ISSUE TITLE
Clipper Modern Style - Resource Button Icon Positioning

### ISSUE THREAD

**Issue by bossloper** [ClipperCMS/ClipperCMS#79] opened 2012-11-22 21:38 UTC
In IE10 when editing or adding a new resource the icons within the buttons for Duplicate, Delete, Cancel and Preview are out of line (shifted to the right). They are shifted so far right that the 'Preview' icon is off screen and the 'Cancel' icon is almost in its place.

They are fine in IE9.

They are also fine in IE10 when just viewing the resource data page so it seems like all icons after the dropdown for 'close, continue editing add another' are affected. I.e. they are shifted right by about the same width as the dropdown list.

ClipperCarbon theme is fine in IE10.

**Comment by microcipcip** [comment] 2012-12-08 19:38
Hi, I am unable to reproduce this issue.
I have actually seen this issue the first time I've loaded the manager, but then I refreshed the page and I can't see it anymore ?!

**Comment by TimGS** [comment] 2012-12-08 19:54
Have Yama's contributions fixed it perhaps?

**Comment by microcipcip** [comment] 2012-12-08 19:59
I don't think so, the contributions where for the tree menu and other areas of the manager.

**Comment by TimGS** [comment] 2012-12-11 15:47
If you are satisfied it's a non-issue, close it.

If other's report the same again, we can always re-open it, but based on the available evidence I suspect it's not an issue now.

**Closed as completed** 2012-12-11 16:24 UTC
