### ISSUE TITLE
Develop branch: No PHP error messages regardless of config setting

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#188] opened 2013-03-03 21:10 UTC
Using latest version of Develop branch (3/3/13), I tried a simple snippet and a simple module with and without syntax errors, and with and without the "display syntax errors on screen" active. No error message was displayed when the syntax error was present, regardless of the Config setting.

Environment: Windows 7 Home Premium 64; Apache 2.4; PHP 5.4.11

**Comment by Cipa** [comment] 2013-03-03 23:41
Same thing happens to me.
1. Plugin PHP errors are not reported in the manager but I can get them
   from php_error.log in MAMP
2. Sql errors(some of them anyway) are reported in manager only if "Should
   PHP/SQL error messages be shown on the screen." is "Show on screen".

From my discussion with Tim the errors are not reported because of the way
they are evaluated, using eval(). That was my understanding anyway.

**Comment by TimGS** [comment] 2013-03-04 18:49
Ignore my earlier message. You're right - this is different from the 'old' behaviour. I'll investigate and fix.

**Comment by TimGS** [comment] 2013-03-05 11:36
Done. Perhaps! I need someone to double check a few things.

Firstly, there was an error (mine ... oops ) in 1.1.0 which resulted in only E_DEPRECATED errors being handled by the parser's error handler if running PHP 5.3+. I have fixed this and made branch clipper-1.1.1 - once someone double checks that all is now OK with branch clipper-1.1.1 I will link to this version from the clippercms.com download page. This is the priority.

Secondly I'm slightly puzzled as to how the parser was flagging up parse errors before, given that in the PHP manual it says _"It is not possible to catch a parse error in eval() using set_error_handler()."_!

Thirdly, the develop branch should now be working as it should, with a few extras. Fatal errors, not previously reported, are now logged, and if required as per the config setting, displayed. In addition empty or missing snippets/plugins (e.g. you call '[!Wibble!] and it doesn't exist) are logged (but in accordance with previous behaviour, execution continues - perhaps this should change?).

**Comment by kp52** [comment] 2013-03-06 23:48
Clipper 1.1.1: Setting "Allow deprecated functions, no error reporting" fails in PHP 5.4 when challenged with deprecated function mysql_list_dbs();

Created snippet containing the function and called it uncached from a page in a fresh install of 1.1.1, on page with minimal template.
Above setting produced error messages:
Deprecated: Function mysql_list_dbs() is deprecated in H:\Clipper-1.1.1\manager\includes\document.parser.class.inc.php(986) : eval()'d code on line 2 Deprecated: mysql_list_dbs(): This function is deprecated; use mysql_query() with SHOW DATABASES instead in H:\Clipper-1.1.1\manager\includes\document.parser.class.inc.php(986) : eval()'d code on line 2 Resource id #23

Setting "Allow deprecated and log" works as advertised

"Do not allow. Throw error and halt" works - displays "Parse error" and relevant details.

**Comment by kp52** [comment] 2013-03-07 10:36
Current Develop branch (7/3/13): same as above, i.e. "Allow deprecated function, no error reporting" puts error message on screen, other options working.
This behaviour also occurs when the "Show errors on screen" setting is "Not displayed. Halt on blank screen"

In addition, the logging for "Allow deprecated and log errors" creates two simultaneous reports, one longer than the other, e.g.
mysql_list_dbs(): This function is deprecated; use mysql_query() with SHOW DATABASES instead; File: H:\Clipper-develop\manager\includes\document.parser.class.inc.php(1156) : eval()'d code; Line: 2 
and
Function mysql_list_dbs() is deprecated; File: H:\Clipper-develop\manager\includes\document.parser.class.inc.php(1156) : eval()'d code; Line: 2

**Comment by TimGS** [comment] 2013-03-07 13:16
@kp52  - what happens when using split(), also deprecated? Also which PHP 5.4 minor version are you using?

I've tried PHP 5.4.12 and I find that almost everything works as intended, except mysql_list_dbs() produces two error messages instead of one for setting "Allow deprecated and log". However setting "Allow deprecated functions, no error reporting" does work as intended as does "Not displayed. Halt on blank screen".

What seems to be happening in your case is that the 'extra' message i.e. "mysql_list_dbs(): This function is deprecated; use mysql_query() with SHOW DATABASES..." is bypassing the Clipper error handler and just causing PHP to exit. In my case it just produces an extra log message (though that is curious in itself).

I also tried on the command line:

php > mysql_list_dbs();
PHP Deprecated:  Function mysql_list_dbs() is deprecated in php shell code on line 1
PHP Deprecated:  mysql_list_dbs(): This function is deprecated; use mysql_query() with SHOW DATABASES instead in php shell code on line 1
php > 

...which implies that PHP is erroneously triggering two E_DEPRECATED error events for mysql_list_dbs(). I don't think there is much we can realistically do about that.

**Comment by kp52** [comment] 2013-03-07 14:30
PHP 5.4.11, Windows 7 Home Premium (64), Apache 2.4
Tried snippet with split, and "Allow deprecated, no error reporting", still have error on the page:

Snippet:

``` <?php
$in = "A,B,C,D";
$str = split(',', $in);

return var_dump($str);
?>
```

 Result:
Deprecated: Function split() is deprecated in H:\Clipper-develop\manager\includes\document.parser.class.inc.php(1156) : eval()'d code on line 3 
array(4) { [0]=> string(1) "A" [1]=> string(1) "B" [2]=> string(1) "C" [3]=> string(1) "D" }

**Comment by kp52** [comment] 2013-03-08 10:31
I have now traced this to the php.ini **display_errors** setting. If it's "on" (default development setting), you get the errors showing on the page and the doubled Clipper logging. 

Comparing behaviour of deprecated against syntax errors, the latter is more helpful in identifying the snippet, while the deprecated logging refers only to "parser" and "evaluated code line NN". If the name of the faulting snippet could be specified, it could save a lot of time tracking down bugs.

**Comment by bossloper** [comment] 2013-03-08 12:01
kp52 - " If the name of the faulting snippet could be specified, it could save a lot of time tracking down bugs." 
That would be a great addition if it is possible! It can sometimes currently be almost impossible to trace on a complex site.

**Comment by TimGS** [comment] 2013-03-08 12:52
I've modified the error handlers to provide more info.

We can override display_errors at runtime, but I'm not sure if we should. It is a development specific setting. Thoughts please?

http://www.php.net/manual/en/errorfunc.configuration.php#ini.display-errors

**Comment by bossloper** [comment] 2013-03-09 17:11
For production I would hide all system errors. 

Not sure if this has been mentioned anywhere, but instead of a blank screen would it make sense to have a custom error page. Some may want to set it up to say 'please contact xyz' or maybe at least indicate to the user that the expected page did not display. A blank page could go unreported for a long time.

**Comment by TimGS** [comment] 2013-03-11 11:22
I'll close this as I think the original issue is fixed.

Matters arising:
1. display_errors - should we override this? Read http://www.php.net/manual/en/errorfunc.configuration.php#ini.display-errors before commenting and consider also the interaction of non-Clipper software and Clipper itself. Setting display_errors at runtime sets it for everything in that run - so if for example I am including Clipper for it's API, from a Wordpress theme, we would be switching off display_errors for Wordpress as well as Clipper. Also bear in mind that any server with this set to on has a server admin who has consciously deemed the site to be a development site, not a live site.
2. More helpful error messages. Implemented. If there are any problems, raise a new issue.
3. Custom error pages. This is probably better posted in the forum Feature Requests section.

**Closed as completed by TimGS** 2013-03-11 11:22 UTC
Labels: bug
