### ISSUE TITLE
weird sql errors on upgrade

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#453] opened 2015-04-24 13:28 UTC
![screen shot 2015-04-24 at 9 24 54 am](https://cloud.githubusercontent.com/assets/293377/7319471/d448e0e6-ea63-11e4-9343-1b08b743cbc5.png)

Any ideas
Running php 5.5 
Maria Db 10.1.2

Clipper reports: Checking MySQL version: OK!   Your MySQL version is: 5.5.5-10.1.2-MariaDB-wsrep-cll-lve

Any ideas?

PS: you can get around and finalize the upgrade process by commenting those 3 sql queries in install/setup.sql

**Comment by TimGS** [comment] 2015-04-24 13:59
setup.sql lines 769-781 contain [.period.]

Try changing this to . in the SQL, or maybe \. in the original PHP (as \ in PHP becomes just \ for the SQL).

-- Tim.

**Comment by TimGS** [comment] 2016-11-28 21:00
Couldn't reproduce myself, but multiple reports now. Fixed on develop.

**Closed as completed by TimGS** 2016-11-28 21:00 UTC
