### ISSUE TITLE
ResManager broken when using russian

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#362] opened 2013-09-01 01:38 UTC
![screen shot 2013-08-31 at 9 37 52 pm](https://f.cloud.github.com/assets/293377/1063327/23008b08-12a7-11e3-8481-639155ecedea.png)

**Comment by kp52** [comment] 2013-09-01 09:14
This is because it's using the Windows-1251 data in assets/modules/resmanager/lang/russian.inc.php
Everything looks fine when the russian-UTF8.inc.php is renamed to russian.inc.php. I think it was decided to standardize on UTF-8 at some point? Certainly that's the character set named in the master frame of the manager.

**Comment by Cipa** [comment] 2013-09-01 11:11
So is renaming the UTF8 version the correct solution?
There are another 2 languages with the same problem: french and sweska

**Comment by alooze** [comment] 2013-09-01 15:32
There are 2 correct solution: rename files or adding back utf-8 lang options for russian, french and sweska in language list.

**Comment by Cipa** [comment] 2013-09-01 15:54
See my solution above: removed invalid files and renamed the utf8 ones so they are now the default ones. If everyone thinks this is the best solution I will do pull request

**Comment by alooze** [comment] 2013-09-01 15:58
it`s fast solution, I`m used this method too. But russian hosters love CP1251 as default encoding forever. I don`t know how about french hosters, but more correct solution IMHO show both non-utf8 and utf8 lang options in config.

**Comment by Cipa** [comment] 2013-09-01 16:05
I searched using google for reasons to use CP1251 but could not find any. Except russians hosters preferring it, are there any good reasons to use it. I am not familiar with any issues that might arise from using UTF8. Can you please post more info about this?

Thank you

**Comment by alooze** [comment] 2013-09-01 16:17
As compromiss we can rename files russian-UTF8 to russian, and russian to russian-1251. This is not question of life. Delete files from install not needed.

Info about issues - russian hosters configured apache & nginx with 1251 default charset. In headers web-server sofware always send this encoding. This is not each&ever, but I see this issues not once.

**Comment by Cipa** [comment] 2013-09-01 16:29
This could work. We'll also have to add the new option in the manager for the 1251 encoding. I don't think we have one unless it's named differently.

Looking at this page http://php.net/manual/en/mbstring.supported-encodings.php 1251 seems to be windows only - Windows-1251 (CP1251). Is this setting ok for unix systems as well?

**Comment by alooze** [comment] 2013-09-01 16:40
I don`t know is french/sweska default encoding 1251. So I can speak about russian only. For russian lang we found 3 solution, and any can be used.

**Comment by alooze** [comment] 2013-09-01 16:48
mbstring function - is for programmers. Users, who can create site with Clipper is not programmers only. Form data validation, filtering in List/Ditto sometime need to use mbstring. 

But our issue about lang files only.

**Comment by TimGS** [comment] 2013-09-01 20:05
A few points:

Manager extras should now convert language arrays to the encoding set in the configuration i.e. $modx_manager_charset which now matches $modx->config['modx_charset']. See get_manager_language.inc.php which does this for the core language files which are all stored as UTF-8.

Previous to Clipper 1.2 all manager pages were UTF-8 (and hence broken if anyone tried to use another character encoding for the frontend - whether any symptoms would be seen would have been dependent on the character sets in question and the characters used on the site).

All manager language files are UTF-8. I'd suggest all extra developers do the same and then convert any language array in a similar way to what get_manager_language.inc.php does for the manager language files (unless of course $modx_manager_charset is UTF-8 anyway). Perhaps the functions in get_manager_language.inc.php need to become API functions for use by extras (?).

Regarding server default character encodings, both the manager and the frontend set content-type headers with a charset. The manager's header.inc.php file also sets this in the <head> via a meta tag. Whether developers put a meta tag for the charset in the frontend's <head> is entirely up to them of course, but they should! As such a server's default character set should be irrelevant - if it is, there is a bug somewhere.

-- Tim.

**Comment by Cipa** [comment] 2013-09-01 21:41
So to be clear if UTF-8 is not detected by the module, we look for the configured character set in the lang files.
In order to properly detect this,  the language files have to be properly named like
russian-iso-8859-1.inc.php
russian-ibm857.inc.php
russian-Windows-1252.inc.php 
or russian-windows-1252.inc.php?

I also found this page (http://www.iana.org/assignments/character-sets/character-sets.xhtml) that has a lot of charsets. Clipper has some that are not in there, if it matters.

**Comment by alooze** [comment] 2013-09-01 21:51
If I understand you question correct, not needed so much charsets. Only default UTF8 in file 'russian.inc.php' and cp1251 (1, not 2) in 'russian-1251.inc.php'. In configuration selectbox we change nothing. If user hosted his site on very russian server, he rename file only.

**Comment by Cipa** [comment] 2013-09-01 22:10
I think we can do the russian as you say but for the rest of the files with the same problem the encoding is not present in the file. I will need some time to look into it, maybe the encoding can be seen in some other way.

In your case the file will be named russian-windows-1252.inc.php as 'windows-1252' is the code that is used by the manager.

**Comment by TimGS** [comment] 2013-09-01 22:45
No need to have one file per charset - that would get incredibly long and impractical. I would suggest storing one file as UTF-8 and perform the conversion if required, as per the manager language files. _As above, please see get_manager_language.inc.php._ If you don't look at this file or see how the manager solves the _same_ problem then you are reinventing the wheel.

As per above, the Russian server issue - or any issue regarding default server configurations and charsets - is a red herring. _The default server charset setting is not used._ If the HTTP headers contain the wrong charset or if the manager meta tag for the charset is missing or incorrect, there is a bug.

**Comment by alooze** [comment] 2013-09-01 23:04
Sorry, I do not know English so well. On the red fish, I lost the thread of the conversation. The method proposed above for the fourth. But the problem is not in the conversion on the fly, the only problem is the confusion - the value of the language setting does not match the name of the file. If it is accepted way to convert on the fly (maybe it is useful to cache the language constants), it is important to only its widespread use.

**Comment by TimGS** [comment] 2013-09-01 23:35
Sorry - "red herring" is a saying in English for something that is leading you into an irrelevant area of thought. In this case server defaults for charsets are not relevant, because Clipper overrides the defaults explicitly.

**Comment by Cipa** [comment] 2013-09-02 03:32
@alooze 
I did the following test and everything works as expected with the russian lang(on a mac with FF)
1. Choose Cyrillic (Windows) - windows-1251 in Character Encoding
2. Choose the Language to be russian
3. Save Configuration

Looking at the manager and Res Manger everything seems to be working. Am I missing something?

**Comment by TimGS** [comment] 2013-09-02 08:36
If you use the Russian language but the character encoding is _not_ Windows 1251 then the text is corrupted because you are trying to display 1251 encoded text on a non-1251 page.

_I've sad it twice already, but please see above two references to get manager language.inc.php!!!!!_ This file solves the IDENTICAL problem for the manager language files, which are ALL stored as UTF8 but converted to the required character encoding if $modx_manager_charset is not UTF8.

This bug is not Russian-specific. _The real issue is that ResManager does not convert it's language files to the character encoding specified in $modx_manager_charset._

**Comment by alooze** [comment] 2013-09-02 09:35
@TimGS 

The real issue is that ResManager **AND TinyMCE** does not convert it's language files to the character encoding specified in $modx_manager_charset.

see screenshot from Configuration below

![download](https://f.cloud.github.com/assets/1949044/1066392/fdacbedc-13b2-11e3-90b2-07275f5c337c.jpeg)

**Comment by TimGS** [comment] 2013-09-02 09:42
I will open a new issue for TinyMCE. Please open a new issue for any other extras (there may be more) that have a similar issues.

**Comment by TimGS** [comment] 2013-09-11 23:59
See https://github.com/ClipperCMS/ClipperCMS/commit/6539eccf759584514fa4087b8a9d4e99d80dedcb This is the fix for List - a similar solution will apply to any extras using language files. It is assumed that the files are stored as UTF-8.

**Comment by TimGS** [comment] 2013-10-07 13:35
Fixed in develop branch.

https://github.com/ClipperCMS/ClipperCMS/commit/06c1458dccade2c2ddd963196030d3a956178924

Please note that the site character set must be suitable for displaying the chosen language's characters e.g. If you select Russian language and ISO-8859-1, the manager will fallback to displaying English text as ISO-8859-1 cannot display Cyrillic characters.

**Closed as completed by TimGS** 2013-10-07 13:35 UTC
